---
- hosts: localhost
  vars:
    git_email: nicolas.comte@arneo-group.fr
    git_name: COMTE Nicolas
    git_diff_so_fancy_enabled: true
    export_ansible_functions: true
  roles:
    - role: default_packages
      tags: ["default_packages"]

    - role: resources
      tags: ["resources"]

    - role: vim
      tags: ["vim"]

    - role: tmux
      tags: ["tmux"]

    - role: shell
      tags: ["shell"]

    - role: git
      tags: ["git"]
